// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJlf0T8PVJK9YfSlVxqWgtb3xBbHm5wTw',
    appId: '1:476879120298:web:7b6641c1a8f08b888aadd3',
    messagingSenderId: '476879120298',
    projectId: 'mentalpulse-6c2f1',
    authDomain: 'mentalpulse-6c2f1.firebaseapp.com',
    storageBucket: 'mentalpulse-6c2f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvG3pwrvNNhsTj6obUb88ZA0JTmnqbxq4',
    appId: '1:476879120298:android:f4ee4c75241322728aadd3',
    messagingSenderId: '476879120298',
    projectId: 'mentalpulse-6c2f1',
    storageBucket: 'mentalpulse-6c2f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCX0QdU-vjLaR1inRydN08fow5NipplwE',
    appId: '1:476879120298:ios:475abcaa1f36640f8aadd3',
    messagingSenderId: '476879120298',
    projectId: 'mentalpulse-6c2f1',
    storageBucket: 'mentalpulse-6c2f1.firebasestorage.app',
    iosBundleId: 'com.example.metalpulse',
  );
}
